### ISSUE TITLE
Clojure syntax error on homepage?

### ISSUE THREAD

**Issue by kreutter** [tadam-framework/tadam-website#4]
On the home page there seems to be a typo IMHO:

https://github.com/tadam-framework/tadam-website/blob/fc912dfa757f49be9c5dc2c0f72f3112720dbd1b/index.pug#L113 and L114:

```clojure
(defn index
  [req]
  (render-HTML req "welcome.html"
    { name: "Tadam",
      time: (System/currentTimeMillis) }))
```
The map passed as third argument to `render-HTML` is not valid Clojure (look at the keys) or is there some macro magic going on? I suspect it should read (keywords as keys):

```clojure
(defn index
  [req]
  (render-HTML req "welcome.html"
    {:name "Tadam",
     :time (System/currentTimeMillis) }))
```
The author might have written way to much JavaScript ;-)

Kindest regards, Stefan

**Comment by tanrax** [comment]
You are absolutely right, too much Javascript in my life hahaha.  thank you ! :)
